// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYguiJYDjfca_Ynt1Vka_gii4nFjm8RXw',
    appId: '1:298244912968:web:e5ea52bf92b5415b31257d',
    messagingSenderId: '298244912968',
    projectId: 'suinobd',
    authDomain: 'suinobd.firebaseapp.com',
    storageBucket: 'suinobd.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7Ee9qw1GQ0jjYSPNai7kjweb6XPZpidU',
    appId: '1:298244912968:android:6173fc767711d4f831257d',
    messagingSenderId: '298244912968',
    projectId: 'suinobd',
    storageBucket: 'suinobd.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYguiJYDjfca_Ynt1Vka_gii4nFjm8RXw',
    appId: '1:298244912968:web:54010705b205e6a131257d',
    messagingSenderId: '298244912968',
    projectId: 'suinobd',
    authDomain: 'suinobd.firebaseapp.com',
    storageBucket: 'suinobd.firebasestorage.app',
  );
}
